### ISSUE TITLE
adapters should not load a second copy of juttle

### ISSUE THREAD

**Issue by demmer** [juttle/juttle#130]
Currently, adapters are loaded using a vanilla node `require()` which can result in a problem if the version of juttle being used is not exactly the same code that ends up being loaded via a call to `require()` in the context of the adapter.

For example, consider the case in which a developer has a copy of juttle and the elastic adapter installed in `~/node_modules` but a second copy checked out in a development directory.

In this case, running `bin/juttle -e 'read elastic...`' will result in the following error:

```
Error: elastic_read cannot be used at the start of a flowgraph. (RT-PROC-CANNOT-START-FLOWGRAPH)
```

The reason for this is that the development copy of juttle was able to resolve `require('juttle-elastic-adapter')` to the code in ~/node_modules, but when the adapter itself calls `require('juttle/lib/runtime')` it ends up loading a second copy of juttle from ~/node_modules.

This means that the instantiated javascript runtime ends up with two copies of `Juttle.proc.source` and the one used by the compiler core is not the same one that was used as the base class for the adapter.

To fix this, we should override the node implementation of `Module._load` using the same technique as https://github.com/mfncooper/mockery and rewrite any require calls so that they reference the juttle runtime that's actually in use and not load a second copy.

**Comment by dmajda** [comment]
I don’t like this solution much because:

  * It solves the problem by “magic” (redefining what `require` means).
  * It legitimizes the setup which lead to the problem.

I’d much rather merely *detect* the situation, produce an error, and force user to change his setup so that the adapter loads modules from the right `juttle`.

By skimming Node’s `module.js` I think the detection can be accomplished by resolving the required path in `Module._load` override using `Module._resolveFilename` and seeing whether it corresponds to the path from the instance that `adapters.js` comes from. If not, throw an exception with a helpful error message, otherwise call the original `Module._load`.

---

All this assumes this is actually a problem worth solving. Given both the implemented and suggested solution is tricky and requires modifying of a private Node.js function I’d say the bar has to be relatively high. So my questions are:

  * What was the reason behind the setup you had?
  * Have anyone beside you run into this in the post-0.1 world?

**Comment by demmer** [comment]
Thanks -- I definitely appreciate your point of view but I still feel like my original solution or something like it is the way to go for a couple reasons:

First of all I think it is a problem worth solving -- @dmehra ran into it the other night when trying to put together a docker container for a demo.

Another thing this enables is a clean set of instructions for how someone could do co-development on juttle and an adapter without needed to do any magic with either `npm link` or manual symlinks inside of `node_modules`.

Consider the case where a developer wants to check out `juttle` and `juttle-xyz-adapter` side-by-side into a working directory. With the current situation, in order to make the runtime able to work properly, the developer would have to create a symlink to the adapter module in either `./node_modules` in the juttle directory (or `~/node_modules`) and a corresponding symlink back to juttle in `./node_modules` of the adapter.

With this change however, the developer can simply specify an explicit `path` to the checked-out code in the adapter config so that juttle can find the adapter, and there's no need for the reverse link because the require magic automatically finds the right version of juttle.

Changing it to detect the problem as opposed to fix the problem seems worse to me -- all we'd be doing is forcing the developer to "fix" it, which may require removing a global installation of juttle that seems irrelevant to working on a developer tree.

However I think it does make sense to log a warning message if we detect that there is a conflict that needs reconciling to make the overall solution less "magic".

I definitely agree that changing the semantics of `require` is a non-trivial decision that we shouldn't do without some thought, but with everything considered I think this is the right thing to do.

**Comment by mstemm** [comment]
I vote for @dmajda's approach--detect but don't try to fix automatically, leaving the fix up to the developer.

**Comment by rlgomes** [comment]
I'm not a fan of automatically fixing things since I think there's room for making mistakes or forcing situations that are much harder to workaround since there's underlying code altering the behavior of something that the developer already has an understanding about its normal behavior. So I :+1: @dmajda's suggestion of detection with a good message around what to do to fix the situation. A detailed message stating where the two juttle versions where found and what to do about fixing this type of thing, which could simply indicate to please read the *Development* section of the `README` where we can put the best practices during development.
