### ISSUE TITLE
tests intermittently hit timeouts in travis

### ISSUE THREAD

**Issue by demmer** [juttle/juttle#14]
We may need to bump up the default test timeout to something greater than 5 seconds due to the occasional slowness in Travis' infrastructure.

For example the following run had two tests fail due to timeouts:
https://travis-ci.org/juttle/juttle/jobs/98195108

**Comment by rlgomes** [comment]
I'm looking into this will have a PR shortly to either increase the 5s timeout to something more reasonable or modify the tests to be better behaved.

**Comment by rlgomes** [comment]
@demmer something else must have happened here since I've ran this test numerous times locally and never seen a runtime over 75ms (the default --slow value). Could this timeout have been triggered by the other bug we saw this run that you're fixing due to the bad parsers tests that were leaving lingering callbacks and intermittently failing ?

**Comment by demmer** [comment]
Oh. That could maybe be the case. I'll put a PR up for that shortly and then we can maybe just close this issue if it doesn't pop up again.

**Comment by rlgomes** [comment]
Bumped up the timeout and haven't seen any more sporadic failures do to slower runtimes in travis. Closing this for the time being.
