### ISSUE TITLE
read -timeField option doesn't work with unix timestamps

### ISSUE THREAD

**Issue by davidbcook** [juttle/juttle#166]
I have a json file that has a field called timestamp with unix timestamp values that look like: 1449012170.2838

When I specify the -timeField 'timestamp' option to read, the time field in the output is "Sat Jan 17 18:30:12 1970 UTC" and does not change. The same thing happens if the values in the timestamp field are integers.

I would love it if unix timestamp fields could be used with -timeField so I wouldn't have to convert them myself.

**Comment by dmehra** [comment]
@dmajda this looks like a useful thing for us to support, see about prioritizing please.

**Comment by mccanne** [comment]
@davidbcook I agree this sounds like a reasonable feature to have.  In the meantime, you should be able to say...

read file -file foo.json | put time=Date.new(timestamp) | remove timestamp | ...

**Comment by demmer** [comment]
I dug into this a little bit -- the juttle core will currently interpret a numeric value as milliseconds since 1970-01-01 while @davidbcook has a value in seconds.

It seems like a sensible default would be to assume any numeric value in a time field is expressed in seconds, unless the value would overflow the maximum date value in which case it is assumed to be milliseconds.

**Comment by dmajda** [comment]
Seeing `-timeUnit` implemented in #170 I wonder: is there actually any real-world data source which regularly produces timestamps with milliseconds as units? Wouldn’t just changing the unit to seconds suffice in practice?

I’d like to avoid adding options if possible, especially if they are to be rarely used. Every option adds some implementation complexity, testing burden, bloats the documentation (meaning it will be less likely read by users), etc.

**Comment by bkutil** [comment]
I think that the ability to specify the time units in general is useful - different sources use different time units (JS/node based apps usually milliseconds, influx supports nanoseconds etc...) and there is no particular reason why to force a particular choice of unit on the client. I also see your point (and agree) in avoiding unnecessary options.

Is there a way how to post-process a point in the same way as the `timeField` + `timeUnit` option would? Something that would basically do `put time = new JuttleMoment(timeField) | remove timeField | ..`. IMHO that, if properly documented, might be a viable alternative, what do you think?

**Comment by davidvgalbraith** [comment]
"Everything is seconds" seems needlessly prescriptive. The six new nonblank lines in https://github.com/juttle/juttle/commit/b6049b329a01b621740922fdd2fb58025c57040d are unlikely to be a documentation dealbreaker. The advantage of having `timeField` and `timeUnit` options to `read` instead of in a downstream `put` is that we can optimize them.

**Comment by dmajda** [comment]
Just to make my position clear: I’m not saying we shouldn’t have the `-timeUnit` option ever at all, I’m just arguing for not adding it speculatively, but *when we have evidence there is a need for it*. By evidence I mean user demand or (because we build a tool/platform) a reasonable use case (e.g. a specific data source we are likely to be connected to which produces timestamps with different unit than seconds by default). So far I didn’t see such a thing, only demand for seconds (the InfluxDB thing @bkutil mentions is irrelevant for `read http` & co.). 

Of course adding one option won’t kill us. It’s the approach we take and feature creep that may result from that. This is why I’m fighting this so vigorously. I don’t want the documentation of our sources to read like `man ls` in 2 years…

**Comment by bkutil** [comment]
> the InfluxDB thing @bkutil mentions is irrelevant for read http & co.

Yeah, I see now that this is about something else and doesn't really apply to influx.

However, I'd still prefer 'using the language to do the task for you' approach (what Steve suggested), instead of adding an option. At least for now.

**Comment by dmehra** [comment]
The problem with "using the language" in the form of put+remove after the read, as mentioned by Dave, is that we don't provide a way to optimize the operation by adapters - both the time assignment, and the downstream `reduce count()` or whatever the program is doing, will have to be done in the juttle runtime. 

Besides that, the approach strikes me as verbose and not easily discoverable by a new user (we'd have to put a note in the `read` docs article about what to do if your time is in non-default units, which is no better than adding the option).

That said, if we have seen no case of reading from a source with ms units, let's just switch the default to seconds and table the addition of `-timeUnit` for later.

**Comment by bkutil** [comment]
> we don't provide a way to optimise the operation by adapters

Thats a very good point.

> Besides that, the approach strikes me as verbose...

On the other hand, it offers flexibility of two options (`timeField`, `timeUnit`), plus a choice of whether to keep or discard the original time field, which we currently remove automatically.

> ...and not easily discoverable by a new user (we'd have to put a note in the read docs article...which is no better than adding the option

We'll have to document the new option in the `read` docs as well :)  I put up a simple docs update in #192 - just to see how describing the language approach might look like in practice. We can close it after we come to conclusion here.

Overall, I'm not against adding this option per-se, but I share the opinion with @dmajda that adapters and views have a lot of options already and we should carefully consider pros and cons of adding another.

**Comment by davidbcook** [comment]
I agree with @dmehra on all points. It would be great to switch the default to seconds as well.

**Comment by dmehra** [comment]
@davidvgalbraith can we merge a version of your PR that would just change the default to seconds? There was unanimous agreement that we should do that part.

**Comment by davidvgalbraith** [comment]
@dmehra it is done! https://github.com/juttle/juttle/pull/244

**Comment by demmer** [comment]
As mentioned by @davidvgalbraith this is done.
