### ISSUE TITLE
http adapter: add support for paging

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle#195]
Support paging in `http read` via -offsetField and -stepField parameters (placeholder names, maybe good enough). 

Rationale: There are many rest-enabled backends that require paging. For example, [orchestrate](https://orchestrate.io/docs/apiref#search) asks for 'offset' and 'limit' parameters in the search URL. The specific field names will vary across APIs so we need to support them through options that let you specify the name. 

The http adapter needs to handle the actual stepping, i.e. incrementing offset = last_offset + limit, and running until all results came back.

**Comment by rlgomes** [comment]
Implemented the easy solution here which is to follow Link header when its provided https://github.com/juttle/juttle/pull/435

Now looking at various APIs (pager duty, elasticsearch, orchestra, github, twilio, new relic) and how they do pagination here is the set of arguments that we would need to provide in order to support the various implementations I've come across:

**offsetField**: name of the field used to keep track of the current offset in terms of points returned, some use offset and some use from.
**offsetFieldStart**: the actual starting value for the offset, may not be necessary as most offsets driven pagination starts at 0.
**pageField**: instead of offsets some APIs such as github, new relic,  likes to use the notion of pages
**pageFieldStart**: because some start at 0 (twilio) and others at 1 (github actually returns the same results for page=0 and page=1 which is quite odd)
**limitField**: the name of the field that contains the actual limit so we can send that along with the URL ? or do we assume the user is setting that themselves ?
**limitfieldValue**: the value for the limit to be passed (otherwise you can't do the math on the offsetField above)

Does this actually seem like something we want to do as I'm feeling that supporting the non [Web Link](https://tools.ietf.org/html/rfc5988) is going to be quite complex 

Links to a few of the paginated APIs I sampled:

https://developer.github.com/guides/traversing-with-pagination/
https://www.elastic.co/guide/en/elasticsearch/guide/current/pagination.html
https://docs.newrelic.com/docs/apis/rest-api-v2/requirements/pagination-api-output
https://developer.pagerduty.com/documentation/rest/pagination
https://orchestrate.io/docs/apiref#graph-get-params
https://www.twilio.com/docs/api/rest/response

@davidvgalbraith @dmajda @dmehra @demmer what do you guys think ?

**Comment by dmajda** [comment]
@rlgomes The option names you suggest all contain “Field” — do they have anything to do with point fields? Or they just specify URL parameters to set? In that case I think they should be named `offsetParam`, `pageParam,` etc. to prevent confusion.

> **limitField**: the name of the field that contains the actual limit so we can send that along with the URL ? or do we assume the user is setting that themselves ?

I don’t get the last question.

> **limitfieldValue**: the value for the limit to be passed (otherwise you can't do the math on the offsetField above)

Maybe just `limitValue`?

Thinking about it, maybe similarly shorten `offsetFieldStart` to `offsetStart` and `pageFieldStart` to `pageStart`?

---

How about bringing back nested options?

```juttle
read http -paging {
    offset: { param: "offset", start: 0 },
    limit: { param: "limit", value: 20 }
}
```

(Just an idea, not 100% sure about this.)

**Comment by demmer** [comment]
@rlgomes I concur with @dmajda that we should use `param` instead of `field`.

>> limitField: the name of the field that contains the actual limit so we can send that along with the URL ? or do we assume the user is setting that themselves ?
> I don’t get the last question.

I think what @rlgomes means is that the limit doesn't change per request, so if the user wants to override the default limit, they can just hard-code it in the url that's passed into the adapter rather than having the adapter set the query parameter. To that end I agree that this seems like an unnecessary set of options to add -- although conceptually related, there actually isn't any need for it.

---

Rather than have two sets of parameters for `offsetParam` / `offsetStart` / `pageParam` / `pageStart` which would necessarily be mutually exclusive, I feel like the following would be conceptually simpler:

**pageParam**: Specifies the query parameter used to enable paging through a large result set with multiple http requests. Default: null (i.e. paging is disabled).
**pageStart**: Initial value of the paging offset. Default: 0
**pageUnit**: Can be either "request" or "record". If set to "request", then each successive http paging request increments the paging parameter by one. If set to "record", then each successive request increments the paging parameter by the number of results returned in the previous request.

---

> How about bringing back nested options?

I'd only want to do this if we then use the same syntactic sugar that we do in views, so that the following would be equivalent:

`read http -paging {param: "page", start: 0}`
`read http -paging.param "page" -paging.start 0`

On balance I don't think I think this would be worth the complexity to explain.

---

Yet another option (which I also don't really like but is worth putting out for discussion) would be to have the adapter support some kind of string interpolation on the url. The user would do something like:

`read http -url "https://api.github.com/repos/juttle/juttle/stargazers?page=$PAGE"`
`read http -url "https://api.orchestrate.io/v0/mycollection/mykey/refs/?limit=100&offset=$OFFSET"`

We would still need to have an option to specify the initial page for odd APIs like github.

**Comment by rlgomes** [comment]
Like the idea of pageStart, pageParam and pageUnit as that covers the current scenarios well while minimizing the number if options to set. I'll have the changes in that other pr by the EOD today so we can review the changes.
