### ISSUE TITLE
Add support for per-adapter modules

### ISSUE THREAD

**Issue by mstemm** [juttle/juttle#325]
This came up in the context of the aws adapter, where the current implementation did automatic aggregations of raw per-item information into aggregates (number of instances), demographics (breakdowns of instances by instance type), etc.

Although useful, it ends up hiding the raw per-item information and isn't in line with the data format returned by our other adapters.

One solution to this would be to define a module that created subgraphs that performed the aggregations (i.e. ec2_demographics() would be a | reduce count=count() by demographic). Juttle users who wanted these automatic rollups could just use the module. However, we don't have a great way to pass around modules in a way they can easily be used by all juttle users.

To address this, how about we allow adapters to publish modules along with their read and write procs? They could be namespaced as Adapter.<adapter_name>.*, and loaded into the juttle runtime when the adapter is loaded. This would allow us to provide useful aggregation methods, constants, etc along with each adapter that could make the raw data easier to use.

**Comment by dmajda** [comment]
I like the idea.

Implementation-wise, I imagine that when an adapter is loaded, the loader would look for a standard directory in its codebase (e.g. `juttle` or `lib/juttle`) and make it so that its contents are visible under a directory with the adapter’s name when loading modules in Juttle.

For example, `import 'aws/demographics' as demographics;` would load `juttle-aws-adapter/juttle/demographics.juttle`.

An obvious question is what just `import 'aws' as aws;` would mean. I’d say let’s establish the same convention as Node.js has with `index.js` files (so it would load would load `juttle-aws-adapter/juttle/index.juttle`). This convention should be applicable everywhere, not just for Juttle files exported by adapters.

**Comment by mstemm** [comment]
Wrt a standard directory, you could also have it returned by the require(). Currently it has properties `read:`, `write:` that name the adapter read and write methods. You could add a `modules:` attribute that points to a file containing the module to load.

**Comment by dmajda** [comment]
Yes, that would probably be more consistent with how adapters currently work. (The advantage of the directory way is that it follows “convention over configuration” with all the usual benefits.)
