### ISSUE TITLE
add adapter api and explicit version

### ISSUE THREAD

**Issue by demmer** [juttle/juttle#367]
To solve some of the challenges we've had in keeping adapters up to date with respect to changes in the juttle runtime, the API used by adapter implementations should be both more clearly defined and explicitly versioned.

Currently adapters `require` various modules from inside the juttle project. This means that when things move around inside the repository (e.g. as happened to JuttleMoment in #312), adapters need to catch up to the changes.

Instead we should have an explicit adapter implementation API. The idea here
would be that the only way adapters would pull in portions of the juttle codebase would be via:

`var AdapterAPI = require('juttle').AdapterAPI(version);`

This module would compose all of the portions of the juttle compiler and runtime
that adapter implementations are allowed to use. This would include:

 * AdapterRead
 * AdapterWrite
 * getLogger
 * types => lib/runtime/types
 * FilterJSCompiler
 * reducerEmptyValue(reducer)
 * testUtils => juttle-test-utils

The `parseTime`, `compileError`, and `runtimeError` utilities would be folded
into methods on the adapter base classes.

Note that as we implement this we will likely find additional modules that
should be included.

In addition, this API should have an explicit semantic version with major and
minor components. Each adapter implementation would include the version of the
API to which it is written. This way the runtime can check if it is compatible
with the version that the implementation wants and throw a user-friendly error
when trying to load an incompatible adapter.

**Comment by demmer** [comment]
@go-oleg This is what we discussed the other day.

@dmajda / @bkutil  / @davidvgalbraith  / @VladVega / @mstemm What do you guys think?

**Comment by mstemm** [comment]
that plan sounds good to me.

**Comment by VladVega** [comment]
lgtm

**Comment by davidvgalbraith** [comment]
Elegant! Downright professional.

**Comment by dmajda** [comment]
For the record, we discussed this with @demmer yesterday. Main points from my side:

  * I totally agree with one goal of the API, which is to specify and narrow the adapter interface. While I understand that exporting an API object will make this interface more explicit than just documentation, I value regularity in the code and thus using normal `require`s for reaching into the `juttle` module.

  * The other goal of the API — providing versioning separate from versioning of the `juttle` package itself — assumes that often, there will be breaking changes in `juttle` which won’t affect the adapter API. This wasn’t the case so far and given our backlog it won’t be the case at least for several releases. From that POV introducing separate versioning may be premature. It is also a new concept which complicates things, so this cost must be considered vs. the cost of problems stemming from keeping just one version (possible “empty” adapter releases which just update the compatibility range).

  * If we go with a separate adapter API version, I’d prefer for the adapters to declare what version range they support (e.g. in `package.json`) rather than actively require an API object of some version from `juttle`. The disadvantage of this approach is that `juttle` can’t provide multiple API versions, but I doubt this will be a problem in practice. The advantage is that we could still use normal `require`s.

**Comment by bkutil** [comment]
I assume that the main challenge with fast moving Juttle core is silent breakage/rot of adapter code - at least this is what I hit w/ influx adapter. (Maybe there are others?)

It looks that there are several approaches to addressing this:

1. Introduce an API
2. Use versioning - allow adapters to throw an error if there was an incompatible update in Juttle core or 'pin' adapter version to a specific version of juttle API - use versioning.
3. Testing process that makes the breakage visible. See Daria's [proposal in Juttle engine](https://github.com/juttle/juttle-engine/issues/4)

My take is that we should definitely do 1. and 3.

1 - An API will provide abstraction and make most changes safer. The interface can be also tested (e.g. for file renames, or basic instantiation). I agree with @dmajda that a simple `require` would be preferable to a loader.

3 - Testing against both master and the stable release will help us notice the breakage faster. See discussion below https://github.com/juttle/juttle-engine/issues/4 for details.

With regards to 2., aren't we trying to duplicate `npm` / `jpm` here? `npm` can already provide dependency tracking, semver checking, error reporting, etc.

So, instead of handling this in the code, I think it might be possible to create a npm package `juttle-adapter-api`, with `juttle` as a dependency. The package would either contain a single `index.js` exposing the API (via an object), or multiple files in lib, each requiring a specific part of Juttle core. It would be accompanied by a set of smoke/basic tests, and the adapters would depend on it. An advantage is independence of versions, using an existing tool with known & tested behaviour and simpler code. Also, this solution is easy to throw away and replace at any time. A disadvantage would be the cost of maintaining and releasing another package.

**Comment by demmer** [comment]
In part due to the spate of problems we've run into over the past couple days with npm installations being not predictable and things not finding each other properly, and taking into account feedback from @dmajda and @bkutil I'm leaning towards a modification of this proposal that removes the need for circular resolution between juttle and the adapters.

Specifically,  the Juttle runtime would export a global `JuttleAdapterAPI` onto which all of the above-mentioned modules would be attached. This would be the only supported way for adapters to access portions of the runtime.

The adapters would not have a peerDependency on juttle. Instead they would include a `juttleAdapterVersion` field in their package.json. This would be checked before loading the adapter. While I think it does make sense to have this be different from the juttle version, in practice we're likely to continue to make changes to the adapter API and other juttle internals for the near term so I agree that we should just use the same 

In addition, this would enable `juttle-service` to directly depend on juttle rather than have it be a peerDependency (if that turned out to be helpful).

While I'm certainly sympathetic to the fact that `require('juttle/path')` is the standard way to reference something from a module, this isn't a standard situation. We fundamentally have a circular dependency between the juttle runtime and the adapters, which is why the prevailing model for npm simply breaks down and even looking at other systems like gulp or grunt plugins isn't a true match for what we want to do.

**Comment by mstemm** [comment]
" Instead they would include a juttleAdapterVersion field in their package.json. This would be checked before loading the adapter. "

How would that work?

**Comment by demmer** [comment]
@mstemm npm allows you to put other things in package.json than the standard 'name', 'dependencies', etc.

So the idea would be that the juttle adapter core would first require() the package.json from the adapter, check that it has a compatible version, then decide to load or not to load accordingly.
