### ISSUE TITLE
Standard error objects for all repos

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle#46]
From @mstemm on 12/03/15:

We should have common error objects used by the various repos. It doesn't have to go so far as shared code pulled in by all the repos. It should at least name conventions for object structure and names.

**Comment by dmajda** [comment]
@mstemm Could you elaborate a bit about what you mean by this and what you are currently missing?

**Comment by dmajda** [comment]
@mstemm Understood, thanks.

I’m not entirely convinced that non-Juttle errors need to use a code and templating mechanism. For a compiler/interpreter this is useful because the same error is often thrown from multiple places and it is good to have the error strings together (so that they tend to be consistent with each other). For an app, these concerns apply much less. And I’m certainly not a fan of putting this into a separate repository.

If this concerns mostly Outrigger, could you take the issue there?

**Comment by mstemm** [comment]
Outrigger already uses the same structure/templating as juttle, so that work is done. This is more of a convention thing so we can just declare success fow now. I'll move and then resolve it.

**Comment by mstemm** [comment]
Oops, I can't actually move, so I'll just resolve.
