### ISSUE TITLE
Decide which events system to use

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle#49]
@mstemm: We should try to use just a single events system. Currently we're mostly using backbone, but maybe we should use node events instead?

@demmer: The reason we use Backbone.events is that it works in the browser and node.js.

@mstemm: matt says now that we use browserify we can use node events in both as well. I don't have a big opinion either way but the run in both advantage of Backbone.events appears to be gone now.

@mnibecker: eventemitter3 is isomorphic and lets us set context unlike node. lets use that.

(Note: "triaged" label on a "question" issue doesn't mean it's been resolved, only that the discussion is cleared to proceed. Our waffle workflow adds that label.)

**Comment by go-oleg** [comment]
I looked into switching to `eventemitter3` and ran into the following problem...

`eventemitter3` uses `.emit()` instead of `.trigger()` to fire events so it may make sense for us to use that as well. However, creates conflict with `.emit()` that our base proc uses to emit points.

It would be a pretty big renaming, but what about changing our current `.emit()` to `.send()` and `.consume()` to `.receive()` so there is some symmetry?

Relevant lines to how procs and the program fire events:

[proc/base.js - .trigger() on a proc is implemented by calling .trigger() on it's program](https://github.com/juttle/juttle/blob/8fdd196e746bc25cb3bde379c60e6617a9a304f9/lib/runtime/procs/base.js#L211-L216)

[program.js - during activation, events is mixed into each node's program](https://github.com/juttle/juttle/blob/8fdd196e746bc25cb3bde379c60e6617a9a304f9/lib/program.js#L47-L49)

[compiler/index.js - add events to the program](https://github.com/juttle/juttle/blob/8fdd196e746bc25cb3bde379c60e6617a9a304f9/lib/compiler/index.js#L49-L60)

**Comment by demmer** [comment]
Another option if we don't want to go this route would be to use event emitter by containment instead of as a mixin and have simple shim methods for trigger/on that dispatch to eventemitter3's emit and on. 

-m

**Comment by dmajda** [comment]
@go-oleg I’m not sure I follow — what exactly is a problem? As far as I can tell, `trigger` in procs just delegates to `this.program.trigger` so changing that to `this.program.emit` should resolve things. Is it bothering you that the original proc method would still be named `trigger`?

If that’s the case, what about just defining `error` and `warning` methods in procs which would do basically what `trigger` does now (just with hard-coded event type)? This would work because we don’t use any other events and would even make the proc code a tiny bit cleaner & shorter.

And for the record, I’m fine with the `emit` → `send` & `consume` → `receive` change and actually like this terminology a bit more (because it is simpler and more symmetric — the opposite of `consume` is really `produce`, not `emit`). But for pragmatic reasons I think I’d prefer to keep the current terminology for now (the change would be pretty big).

**Comment by go-oleg** [comment]
Yes, that was my concern. I also might've gotten a little lost in the code and thought I'd seen instances of `program.events.trigger()` being called and didn't want the `program.trigger()` and `program.events.emit()` discrepancy to show up there, but I don't think thats a actually in there.

So I think `proc.trigger()` calling `proc.program.emit()` is fine. Don't have a particularly strong opinion on that vs dedicated `error` and `warning` methods.
