### ISSUE TITLE
Add a ? operator for FTS

### ISSUE THREAD

**Issue by dmehra** [juttle/juttle#56]
Instead of naked strings implying FTS, we should have an operator for the expressions to avoid confusion, especially now that most backends won't support it. (Currently, only `elastic` and `gmail` adapters support FTS.)

- [x] Add spec / design doc (move content from Confluence)
- [ ] Modify grammar
- [ ] Update docs
- [ ] Update examples

**Comment by dmajda** [comment]
Copying internal proposal written by @demmer here:

## Option 1: Unary Search Operator

Today a standalone string term in a filter expression is interpreted as a full text search for that term across all fields. This design was motivated by comparisons to the splunk language as well as the fact that we wanted to emphasize the search capability. However it is somewhat non-intuitive for a new user, so this proposal would the ? operator to indicate search.

For example the following would search for the string "error" in all fields and map the value "syslog" in the "appname" field:

```juttle
read elastic ? 'error' appname='syslog'
```

Searching for multiple terms would require multiple ? operators:

```
read elastic ? 'error' ? 'host123' appname='syslog'
```

## Option 2: Binary Search Operator:

Internally, FTS is implemented using the magic _all field in elasticsearch, which tells it to search across all fields and not just a specific field.

We could mimic those semantics in Juttle and make search a binary operator instead of a unary operator, and pass through _all as the hook to enable current behavior. For example:
 
```
read elastic _all?'error' appname='syslog'
```

If we were to do this ?= reads slightly better:

```
read elastic _all?='error' appname='syslog'
```

At that point it would be trivial to support FTS on a single field (which we can't do today):

```
read elastic message?='error' appname='syslog'
```

On balance it seems like the unary operator approach is cleaner than the _all magic field.

**Comment by dmajda** [comment]
@demmer I’d like to discuss this tomorrow and ideally arrive to a resolution on the design so I can start implementing. Beside being important by itself I’d like to do this before I dive into #57.

**Comment by dmajda** [comment]
The result of discussion with @demmer is that we’ll implement Option 1, but with `?=` as the operator:

```
read elastic ?= 'error' appname='syslog'
```

**Comment by dmajda** [comment]
After implementing this change (#232) me + @demmer agreed the new syntax looks ugly and we decided to scrap the whole idea of the FTS operator.
